image: node:latest

include:
  # Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
  - template: Security/Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build:css
  artifacts:
    paths:
      - public/styles/*

deploy_production:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u gitlab,${FTP_PASS} ftp://www.davidsandoz.ch; mirror -Rev public/ ./ --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/ --exclude vcards/"
  environment:
    name: production
    url: https://davidsandoz.ch
  only:
    - main
