image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build:css
# deploy_production:
#   stage: deploy
#   script:
#   environment:
#     name: production
#     url: https://davidsandoz.ch
#   only:
#   - master
