image: node:latest

include:
  # Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
  - template: Security/Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
